# Gemfile
source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'  # Provides helpers like JSON serialization
gem 'sqlite3'          # Example database
gem 'sinatra-activerecord'
gem "rake"
